### 1.

#### a.

In [79]:
import numpy as np

# matrices para multiplicar
A = np.array([[2, -3], [3, -1]])
B = np.array([[1, 5], [2, 0]])

# Multiplicación de matrices
C = np.dot(A, B)
print("Producto de matrices A y B:\n", C)

Producto de matrices A y B:
 [[-4 10]
 [ 1 15]]


#### b.

In [85]:
A = np.array([[2, -3], [3, -1]])
B = np.array([[1, 5, -4], [-3, 2, 0]])

# Multiplicación de matrices
C = np.dot(A, B)
print("Producto de matrices A y B:\n", C)

Producto de matrices A y B:
 [[ 11   4  -8]
 [  6  13 -12]]


#### c.

In [88]:
A = np.array([[2, -3, 1], [4, 3, 0], [5, 2, -4]])
B = np.array([[0, 1, -2], [1, 0, -1], [2, 3, -2]])

# Multiplicación de matrices
C = np.dot(A, B)
print("Producto de matrices A y B:\n", C)

Producto de matrices A y B:
 [[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


#### d.

In [91]:
A = np.array([[2, 1, 2], [-2, 3, 0], [2, -1, 3]])
B = np.array([[1, -2], [-4, 1], [0, 2]])

# Multiplicación de matrices
C = np.dot(A, B)
print("Producto de matrices A y B:\n", C)

Producto de matrices A y B:
 [[ -2   1]
 [-14   7]
 [  6   1]]


### 2.

In [11]:
A = np.array([[4, 2, 6], 
              [3, 0, 7],
              [-2, -1, -3],
             ])

# Determinante de la matriz
det_A = np.linalg.det(A)
print("Determinante de A:", det_A)

# Verificar si la matriz es no singular
if det_A != 0:
    A_inv = np.linalg.inv(A)
    print("Inversa de A:\n", A_inv)
else:
    print("La matriz A es singular y no tiene inversa.")

Determinante de A: 0.0
La matriz A es singular y no tiene inversa.


In [15]:
B = np.array([[1, 2, 0], 
              [2, 1, -1],
              [3, 1, 1],
             ])
# Determinante de la matriz
det_B = np.linalg.det(B)
print("Determinante de B:", det_B)

# Verificar si la matriz es no singular
if det_B != 0:
    B_inv = np.linalg.inv(B)
    print("Inversa de B:\n", B_inv)
else:
    print("La matriz B es singular y no tiene inversa.")

Determinante de B: -8.000000000000002
Inversa de B:
 [[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]


In [17]:
C = np.array([[1, 1, -1, 1], 
              [1, 2, -4, -2],
              [2, 1, 1, 5],
              [-1, 0, -2, -4]
             ])
# Determinante de la matriz
det_C = np.linalg.det(C)
print("Determinante de C:", det_C)

# Verificar si la matriz es no singular
if det_C != 0:
    C_inv = np.linalg.inv(C)
    print("Inversa de C:\n", C_inv)
else:
    print("La matriz C es singular y no tiene inversa.")

Determinante de C: 0.0
La matriz C es singular y no tiene inversa.


In [19]:
D = np.array([[4, 0, 0, 0], 
              [6, 7, 0, 0],
              [9, 11, 1, 0],
              [5, 4, 1, 1]
             ])
# Determinante de la matriz
det_D = np.linalg.det(D)
print("Determinante de D:", det_D)

# Verificar si la matriz es no singular
if det_D != 0:
    D_inv = np.linalg.inv(D)
    print("Inversa de D:\n", D_inv)
else:
    print("La matriz D es singular y no tiene inversa.")

Determinante de D: 28.00000000000001
Inversa de D:
 [[ 2.50000000e-01 -2.77555756e-17  0.00000000e+00  0.00000000e+00]
 [-2.14285714e-01  1.42857143e-01 -0.00000000e+00 -0.00000000e+00]
 [ 1.07142857e-01 -1.57142857e+00  1.00000000e+00 -0.00000000e+00]
 [-5.00000000e-01  1.00000000e+00 -1.00000000e+00  1.00000000e+00]]


### 3.

In [23]:
# matriz de coeficientes
A = np.array([[1, -1, 2, -1], [1, 0, -1, 1], [2, 1, 3, -4], [0, -1, 1, -1]])
b1 = np.array([6, 4, -2, 5])

# Resolver el sistema lineal Ax = b
x = np.linalg.solve(A, b1)
print("Solución del sistema lineal:", x)

Solución del sistema lineal: [ 3. -6. -2. -1.]


In [25]:
# matriz de coeficientes
A = np.array([[1, -1, 2, -1], [1, 0, -1, 1], [2, 1, 3, -4], [0, -1, 1, -1]])
b2 = np.array([1, 1, 2, -1])

# Resolver el sistema lineal Ax = b
x = np.linalg.solve(A, b2)
print("Solución del sistema lineal:", x)

Solución del sistema lineal: [1. 1. 1. 1.]


### 4.

In [32]:
# Matriz con variable A
A = np.array([[1, -1, 'A'], [2, 2, 1],[0, 'A', -3/2]])

# Determinante de la matriz
from sympy import Symbol, Matrix

A_var = Symbol('A')
matrix = Matrix([[1, -1, A_var], [2, 2, 1],[0, A_var, -3/2]])
det_matrix = matrix.det()
print("Determinante de la matriz:", det_matrix)

# Solucionar para que el determinante sea 0
from sympy import solve

values = solve(det_matrix, A_var)
print("Valores de A que hacen la matriz singular:", values)

Determinante de la matriz: 2*A**2 - A - 6.0
Valores de A que hacen la matriz singular: [-1.50000000000000, 2.00000000000000]


### 5.

In [35]:
import numpy as np

# Sistema a
A1 = np.array([
    [1, 0, 0],
    [2, 1, 0],
    [-1, 0, 1]
])
B1 = np.array([
    [2, 3, -1],
    [0, -2, 1],
    [0, 0, 3]
])
C1 = np.array([2, -1, 1])

# Sistema b
A2 = np.array([
    [2, 0, 0],
    [-1, 1, 0],
    [3, 2, -1]
])
B2 = np.array([
    [1, 1, 1],
    [0, 1, 2],
    [0, 0, 1]
])
C2 = np.array([-1, 3, 0])

# Resolver el sistema a
X1 = np.linalg.solve(np.dot(A1, B1), C1)

# Resolver el sistema b
X2 = np.linalg.solve(np.dot(A2, B2), C2)

print("Solución para el sistema a:")
print(X1)

print("Solución para el sistema b:")
print(X2)

Solución para el sistema a:
[-3.  3.  1.]
Solución para el sistema b:
[ 0.5 -4.5  3.5]


### 6.

In [39]:
import numpy as np
from scipy.linalg import lu

# Matrices del ejercicio (a, b, c, d)
matrices = [
    np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]]),
    np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]]),
    np.array([[2, 0, 0], [1, 1.5, 0], [0, -3, 0.5], [2, -2, 1]]),
    np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6.0000, 0, 1.1973], [-1.0000, -5.2107, 1.1111, 0], [6.0235, 7.0000, 0, -4.1561]])
]

for i, A in enumerate(matrices):
    # Factorización LU
    P, L, U = lu(A)

    print(f"\nMatriz {chr(97 + i)}:")  # Imprime a, b, c, d
    print("Matriz P:\n", P)
    print("Matriz L:\n", L)
    print("Matriz U:\n", U)



Matriz a:
Matriz P:
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
Matriz L:
 [[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 1.         -0.          1.        ]]
Matriz U:
 [[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]

Matriz b:
Matriz P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
Matriz L:
 [[ 1.          0.          0.        ]
 [-0.68685567  1.          0.        ]
 [ 0.32603093 -0.21424728  1.        ]]
Matriz U:
 [[ 3.104      -7.013       0.014     ]
 [ 0.         -0.72091881 -7.00338402]
 [ 0.          0.          1.59897957]]

Matriz c:
Matriz P:
 [[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
Matriz L:
 [[ 1.          0.          0.        ]
 [ 0.          1.          0.        ]
 [ 1.          0.66666667  1.        ]
 [ 0.5        -0.5         0.375     ]]
Matriz U:
 [[ 2.          0.          0.        ]
 [ 0.         -3.          0.5       ]
 [ 0.          0.          0.66666667]]

Matriz d:
Matriz P:
 [[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0

### 7.

In [49]:
def eliminacion_gaussiana_lu(A: np.ndarray) -> (np.ndarray, np.ndarray):
    """Descompone una matriz A en matrices L y U usando eliminación gaussiana.

    ## Parameters

    ``A``: matriz de coeficientes del sistema de ecuaciones lineales. Debe ser de tamaño n-by-n.

    ## Return

    ``L``: matriz triangular inferior.
    ``U``: matriz triangular superior.
    """
    if not isinstance(A, np.ndarray):
        A = np.array(A)
    assert A.shape[0] == A.shape[1], "La matriz A debe ser cuadrada."
    n = A.shape[0]

    L = np.eye(n)
    U = A.copy()

    for i in range(0, n - 1):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if U[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(U[pi, i]) < abs(U[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            U[[i, p], :] = U[[p, i], :]
            L[[i, p], :i] = L[[p, i], :i]

        # --- Eliminación: loop por fila
        for j in range(i + 1, n):
            m = U[j, i] / U[i, i]
            U[j, i:] = U[j, i:] - m * U[i, i:]
            L[j, i] = m


    return L, U

In [51]:
def resolver_sistema_lu(L: np.ndarray, U: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales utilizando matrices L y U.

    ## Parameters

    ``L``: matriz triangular inferior.
    ``U``: matriz triangular superior.
    ``b``: vector de términos independientes.

    ## Return

    ``x``: vector con la solución del sistema de ecuaciones lineales.
    """
    n = L.shape[0]

    # Resolviendo Ly = b
    y = np.zeros_like(b)
    for i in range(n):
        y[i] = b[i] - sum(L[i, j] * y[j] for j in range(i))

    # Resolviendo Ux = y
    x = np.zeros_like(b)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - sum(U[i, j] * x[j] for j in range(i + 1, n))) / U[i, i]

    return x

#### a.

In [61]:
A = np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]])
b = np.array([-1, 0, 4]) 

# Descomposición LU
L, U = eliminacion_gaussiana_lu(A)

# Resolver sistema lineal utilizando L y U
x = resolver_sistema_lu(L, U, b)
print("Solución del sistema lineal:", x)

Solución del sistema lineal: [ 1  2 -1]


#### b.

In [64]:
A = np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]])
b = np.array([1.984, -5.049, -3.895])

# Descomposición LU
L, U = eliminacion_gaussiana_lu(A)

# Resolver sistema lineal utilizando L y U
x = resolver_sistema_lu(L, U, b)
print("Solución del sistema lineal:", x)

Solución del sistema lineal: [1. 1. 1.]


### c.

In [66]:
A = np.array([[2, 0, 0, 0], [1, 1.5, 0, 0], [0, -3, 0.5, 0], [2, -2, 1, 1]])
b = np.array([3, 4.5, -6.6, 0.8])

# Descomposición LU
L, U = eliminacion_gaussiana_lu(A)

# Resolver sistema lineal utilizando L y U
x = resolver_sistema_lu(L, U, b)
print("Solución del sistema lineal:", x)

Solución del sistema lineal: [  2.25   0.5  -10.2    7.5 ]


#### d.

In [68]:
A = np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6.0000, 0, 1.1973], [-1.0000, -5.2107, 1.1111, 0], [6.0235, 7.0000, 0, -4.1561]])
b = np.array([17.102, -6.1593, 3.0004, 0.0000])

# Descomposición LU
L, U = eliminacion_gaussiana_lu(A)

# Resolver sistema lineal utilizando L y U
x = resolver_sistema_lu(L, U, b)
print("Solución del sistema lineal:", x)

Solución del sistema lineal: [ 3.10093094  1.25924266 24.08826091  6.61513347]
